with Types_From; use Types_From;
with Types_To;   use Types_To;

package body Position_Mappers is
   --  Generated by tools/gen_mapper.py — DO NOT EDIT.
   function Map (X : Types_From.T_Position_From_GPS) return Types_To.T_Position_To_Station is
     ( Lat => T_Integer16 (X.Latitude),
       Long => T_Integer16 (X.Longitude),
       Speed => Map(X.Speed) );
   function Map (X : Types_From.T_Speed) return Types_To.T_Speed is
     ( North => T_Float_16 (X.North),
       East => T_Float_16 (X.East),
       Down => T_Float_16 (X.Down) );

end Position_Mappers;
