with Types_From;
with Types_To;

package Position_Mappers is
   --  Generated by tools/gen_mapper.py — DO NOT EDIT.
   function Map (X : Types_From.T_Position_From_GPS) return Types_To.T_Position_To_Station;
   function Map (X : Types_From.T_Speed) return Types_To.T_Speed;

end Position_Mappers;
