with Types_From;
with Types_To;

package Position_Mappers is
   --  Generated by tools/gen_mapper.py — DO NOT EDIT.
   function Map (X : Types_From.T_Position_From_GPS) return Types_To.T_Position_To_Station;
   function Map (X : Types_From.T_Speed) return Types_To.T_Speed;
   function Map (X : Types_From.T_Satellite) return Types_To.T_Satellite;
   function Map (X : Types_From.T_Position) return Types_To.T_Position;
   function Map (A : Types_From.T_Satellites) return Types_To.T_Satellites;
   function Map (E : Types_From.T_Status) return Types_To.T_Status;

end Position_Mappers;
